package com.harudle.auth.infrastructure.oauth;

public enum OAuthFailureReason {

    PROVIDER_ACCESS_DENIED,
    PROVIDER_AUTHENTICATION_FAILED,
    INVALID_PROVIDER_PROFILE,
    REQUIRED_PROFILE_MISSING,
    INACTIVE_USER,
    UNSUPPORTED_PROVIDER,
    INTERNAL_CONSISTENCY_ERROR,
    INTERNAL_ERROR
}
