-- Feed profile extension. UUIDs continue to be generated by the application.
-- NULL nickname keeps the existing name as the display fallback, including
-- duplicate/long legacy names. nickname_reservations is intentionally omitted.
-- The profile service must check requested nicknames against legacy name fallbacks
-- as well as assigned nicknames; the index below arbitrates concurrent assignments.

ALTER TABLE users
    ADD COLUMN nickname VARCHAR(30) COLLATE "C",
    ADD COLUMN profile_image_code SMALLINT;

ALTER TABLE users
    ADD CONSTRAINT ck_users_nickname
        CHECK (
            nickname IS NULL
            OR (
                char_length(nickname) BETWEEN 1 AND 10
                AND nickname !~ '^[[:space:]]|[[:space:]]$'
                AND nickname IS NFC NORMALIZED
            )
        ),
    ADD CONSTRAINT ck_users_profile_image_code
        CHECK (profile_image_code IS NULL OR profile_image_code BETWEEN 1 AND 5);

CREATE UNIQUE INDEX uq_users_active_nickname
    ON users (nickname)
    WHERE nickname IS NOT NULL AND deleted_at IS NULL;

-- Assign an existing member's default image once; keep guest profiles nullable.
-- The UUID-derived choice is stable and avoids changing the original name.
-- New member profile assignment remains the responsibility of the profile service.
UPDATE users AS member
SET profile_image_code = (1 + get_byte(uuid_send(member.id), 15) % 5)::SMALLINT
WHERE member.deleted_at IS NULL
  AND NOT EXISTS (
      SELECT 1 FROM guest_sessions AS guest
      WHERE guest.guest_user_id = member.id
  );
