-- Harudle production schema for PostgreSQL.
-- UUID values are generated by the application.

CREATE TABLE users (
    id UUID NOT NULL,
    primary_email VARCHAR(320),
    name VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,

    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE oauth_accounts (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    user_id UUID NOT NULL,
    provider VARCHAR(20) NOT NULL,
    provider_subject VARCHAR(255) NOT NULL,
    provider_email VARCHAR(320),
    last_login_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_oauth_accounts PRIMARY KEY (id),
    CONSTRAINT uq_oauth_accounts_provider_subject
        UNIQUE (provider, provider_subject),
    CONSTRAINT uq_oauth_accounts_user_provider
        UNIQUE (user_id, provider),
    CONSTRAINT fk_oauth_accounts_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE
);

CREATE TABLE refresh_tokens (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    user_id UUID NOT NULL,
    token_hash CHAR(64) NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_refresh_tokens PRIMARY KEY (id),
    CONSTRAINT uq_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE
);

CREATE TABLE diaries (
    id UUID NOT NULL,
    user_id UUID NOT NULL,
    diary_date DATE NOT NULL,
    source_text VARCHAR(300) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,

    CONSTRAINT pk_diaries PRIMARY KEY (id),
    CONSTRAINT fk_diaries_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE
);

CREATE TABLE daily_generation_usage (
    user_id UUID NOT NULL,
    usage_date DATE NOT NULL,
    used_count INTEGER NOT NULL DEFAULT 0,
    limit_count INTEGER NOT NULL DEFAULT 3,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_daily_generation_usage
        PRIMARY KEY (user_id, usage_date),
    CONSTRAINT ck_daily_generation_usage_count
        CHECK (
            used_count >= 0
            AND limit_count >= 0
            AND used_count <= limit_count
        ),
    CONSTRAINT fk_daily_generation_usage_user
        FOREIGN KEY (user_id)
        REFERENCES users (id)
        ON DELETE CASCADE
);

CREATE TABLE generation_prompts (
    id BIGINT GENERATED ALWAYS AS IDENTITY,
    prompt_text TEXT NOT NULL,
    image_asset_object_key VARCHAR(1024),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_generation_prompts PRIMARY KEY (id),
    CONSTRAINT ck_generation_prompts_image_asset_key_length
        CHECK (
            image_asset_object_key IS NULL
            OR octet_length(image_asset_object_key) <= 1024
        )
);

CREATE TABLE comic_generations (
    id UUID NOT NULL,
    diary_id UUID NOT NULL,
    prompt_id BIGINT NOT NULL,
    idempotency_key UUID NOT NULL,
    request_fingerprint CHAR(64) NOT NULL,
    status VARCHAR(20) NOT NULL,
    storyboard JSONB,
    title VARCHAR(100),
    image_object_key VARCHAR(1024),
    error_code VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMPTZ,

    CONSTRAINT pk_comic_generations PRIMARY KEY (id),
    CONSTRAINT uq_comic_generations_diary UNIQUE (diary_id),
    CONSTRAINT uq_comic_generations_idempotency UNIQUE (idempotency_key),
    CONSTRAINT uq_comic_generations_image_key UNIQUE (image_object_key),
    CONSTRAINT ck_comic_generations_request_fingerprint
        CHECK (request_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_comic_generations_image_key_length
        CHECK (
            image_object_key IS NULL
            OR octet_length(image_object_key) <= 1024
        ),
    CONSTRAINT ck_comic_generations_status
        CHECK (status IN ('PROCESSING', 'SUCCEEDED', 'FAILED')),
    CONSTRAINT fk_comic_generations_diary
        FOREIGN KEY (diary_id)
        REFERENCES diaries (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_comic_generations_prompt
        FOREIGN KEY (prompt_id)
        REFERENCES generation_prompts (id)
        ON DELETE RESTRICT
);

CREATE TABLE share_links (
    id UUID NOT NULL,
    generation_id UUID NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_share_links PRIMARY KEY (id),
    CONSTRAINT uq_share_links_generation UNIQUE (generation_id),
    CONSTRAINT fk_share_links_generation
        FOREIGN KEY (generation_id)
        REFERENCES comic_generations (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_refresh_tokens_user_id
    ON refresh_tokens (user_id);

CREATE INDEX idx_refresh_tokens_expires_at
    ON refresh_tokens (expires_at);

CREATE INDEX idx_diaries_user_id
    ON diaries (user_id);

CREATE INDEX idx_diaries_user_timeline
    ON diaries (user_id, diary_date DESC, id DESC)
    WHERE deleted_at IS NULL;

CREATE INDEX idx_comic_generations_prompt_id
    ON comic_generations (prompt_id);
