services:
  backend:
    volumes:
      - type: bind
        source: /etc/harudle/gcp/gcp-wif.json
        target: /var/run/harudle/gcp-wif.json
        read_only: true
        bind:
          create_host_path: false
    logging: !override
      driver: awslogs
      options:
        awslogs-region: "${AWS_REGION:-ap-northeast-2}"
        awslogs-group: "/harudle/dev/backend"
        awslogs-create-group: "false"

  frontend:
    logging: !override
      driver: awslogs
      options:
        awslogs-region: "${AWS_REGION:-ap-northeast-2}"
        awslogs-group: "/harudle/dev/frontend-nginx"
        awslogs-create-group: "false"
