services:
  backend:
    logging: !override
      driver: awslogs
      options:
        awslogs-region: "${AWS_REGION:-ap-northeast-2}"
        awslogs-group: "/harudle/dev/backend"
        awslogs-create-group: "false"

  frontend:
    logging: !override
      driver: awslogs
      options:
        awslogs-region: "${AWS_REGION:-ap-northeast-2}"
        awslogs-group: "/harudle/dev/frontend-nginx"
        awslogs-create-group: "false"
